version: '3'

services:

  team-pong-node:
    volumes:
      - frontend:/frontend
    environment:
      - LEGAL_LINK
    build:
      context: ..
      dockerfile: backend/node/Dockerfile

  team-pong-flask:
    build:
      context: ..
      dockerfile: ./backend/flask/Dockerfile
    volumes:
      - ./app:/app
      - frontend:/frontend
    environment:
      - FLASK_APP=app/server.py
      - FLASK_DEBUG
      - PORT
      - PY_DEBUG_PORT
      - PYTHONUNBUFFERED=1
      - GEVENT_SUPPORT=True
      - 'RUN=python -Xfrozen_modules=off -u -m debugpy --listen 0.0.0.0:$PY_DEBUG_PORT -m gunicorn -c /app/gunicorn_conf.py app.__main__:app --reload'
    command: python -Xfrozen_modules=off -u -m debugpy --listen 0.0.0.0:$PY_DEBUG_PORT -m gunicorn -c /app/gunicorn_conf.py app.__main__:app --reload
    ports:
      - "127.0.0.1:$PY_DEBUG_PORT:$PY_DEBUG_PORT"

  team-pong-nginx:
    image: nginx:1.21.1
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/proxy_params:/etc/nginx/proxy_params
    ports:
      - "127.0.0.1:${PORT}:80"


volumes:
  frontend: